### ISSUE TITLE
Bug at Room class

### ISSUE THREAD

**Issue by daimonkor** [doorbash/colyseus-java#1]
Please fix using room callback

http://prntscr.com/mll5wl

Problems:
1. my server sent onAuth failed but I got onClose, but I think that it is valid onError http://prntscr.com/mll6t3
2. you removed all listeners before calling onLeave callback function

Thanks for help.

**Comment by doorbash** [comment]
Thanks @daimonkor for sharing. Just released `v1.1.1` to fix this. Cheers!

**Comment by daimonkor** [comment]
@doorbash Hi, wow, flash update, thanks, but I think check on string is not right, because server can change template response http://prntscr.com/mltll1 . Maybe there is check on response code 401. Thanks for your support.

**Comment by doorbash** [comment]
I don't know maybe i should change it to something like this:

```
if (code == CloseFrame.PROTOCOL_ERROR && reason != null && reason.startsWith("Invalid status code received: 401")) {
    for (Listener listener : listeners) {
        listener.onError(new Exception(reason));
    }
}
```
but i think it's ok for now

**Comment by daimonkor** [comment]
Maybe containts string "401 Unauthorized" with ignore case sensetive

**Comment by doorbash** [comment]
@daimonkor you have a specific case in mind that in current solution `onError` method does not get called when server rejects authentication?

**Comment by daimonkor** [comment]
@doorbash No, but I think server (newest release) can send different message about onAuth failed and my opinion that check on substring "401 Unauthorized" (ignore case sensetive) is more valid.

**Comment by doorbash** [comment]
ok then feel free to re-open this if you had issue with a specific web server
i close #2 for now
thanks for your help

**Comment by daimonkor** [comment]
@doorbash ok, thank you for support.
