### ISSUE TITLE
Updates for 0.11

### ISSUE THREAD

**Issue by endel** [doorbash/colyseus-java#11]
Hey @doorbash!

As you may know, I'm working on version `0.11` of the server - hopefully, it won't be difficult to implement the changes in the client for Java.

The `Client` class has been simplified a lot. The matchmaking now occurs in an HTTP request instead of a WebSocket connection: https://github.com/colyseus/colyseus.js/blob/0.11/src/Client.ts#L31-L93

The `Room` had very few changes:
- The `options` member is not necessary anymore (https://github.com/doorbash/colyseus-java/blob/master/src/main/java/io/colyseus/Room.java#L142)
- The `sessionId` is not coming in the `JOIN_ROOM` message anymore (these lines can be removed https://github.com/doorbash/colyseus-java/blob/master/src/main/java/io/colyseus/Room.java#L204-L205)
- The `id` of the Room is not being sent as part of `ROOM_DATA` anymore (no need to send `this.id` here https://github.com/doorbash/colyseus-java/blob/master/src/main/java/io/colyseus/Room.java#L300)

It would be great if you can keep this client up-to-date! 🙏 
Cheers! <3

**Comment by doorbash** [comment]
Alright thanks for the heads up @endel 
I will adapt the client withnew changes very soon :)

**Comment by doorbash** [comment]
Hi @endel It's done (I hope!) https://github.com/doorbash/colyseus-java/pull/12
I've tested it in `agar.io-clone` game. It works pretty good!
Let me know if there is any issue with it.

**Comment by doorbash** [comment]
https://github.com/doorbash/agar.io-clone/blob/0.11/client/core/src/ir/doorbash/agar/io/Game.java#L228-L277

**Comment by endel** [comment]
Awesome @doorbash, thanks for making this so quickly! 

![shipit](https://user-images.githubusercontent.com/130494/63563565-df324e80-c537-11e9-9f06-331ca0d14784.jpeg)
