### ISSUE TITLE
Refactor Client

### ISSUE THREAD

**Issue by daimonkor** [doorbash/colyseus-java#3]
Hi, @doorbash 
1. Please provide additional param to "close" client connection - "leaveRoom". Default value must be false (maybe useful while android lifecycle pause/rotate - only disconnect). If developer manully call "close(true)" - additional action is leave from joined room. http://prntscr.com/mm3zme . My use case is singleton client and I am providing state - reset client http://prntscr.com/mm3veu. So I have "connect" and "stop" functions. It is useful when user call more times dialog create/connect game - show dialog (connect to server: create room or get available rooms), close dialog (disconnect from server with leave room). 
2. Please Client "connect" function change to public and remove from constructor. I have some overhead for using "connect" function now. 
3. Please add new function "setListener" to Client class

Thanks for help.

**Comment by doorbash** [comment]
Hi @daimonkor I could do these things specially number 2 and 3 in your list but I tried to make it look more like the official Colyseus clients. see [colyseus-unity3d/.../Client.cs](https://github.com/colyseus/colyseus-unity3d/blob/master/Assets/Plugins/Colyseus/Client.cs) and [colyseus.js/.../Client.ts](https://github.com/colyseus/colyseus.js/blob/master/src/Client.ts) for example.
You can always fork the repo and change it the way you like.
Thanks for your suggestions.

**Comment by daimonkor** [comment]
Hi, @doorbash What do you think about my list number 1? I mean singleton with "connect" and "stop" functions?

**Comment by doorbash** [comment]
I don't know much Kotlin but I see you're extending Client class and invoking supper class with reflection. You can remove `room` field in your class and use `client.rooms` instead to make it support multiple rooms. You should clone the repository and do num2 and 3, then you can call `Client.connect` and add `setListener` without using Reflection.

**Comment by daimonkor** [comment]
@doorbash ok. thanks

**Comment by daimonkor** [comment]
@doorbash What do you think about URL encoding room connection options http://prntscr.com/mm8nll . I got crush when using invalid uri symbols. http://prntscr.com/mm8o8v http://prntscr.com/mm8orl

I don`t know how it is valid, maybe auto encode to UTF-8 while send message and auto decode at server

**Comment by doorbash** [comment]
ok I think that's a bug and I have to fix that. nice catch @daimonkor  👍

**Comment by daimonkor** [comment]
@doorbash Thanks a lot, the same bug found at C# and js versions

**Comment by doorbash** [comment]
No i've just tested js version. it's fine with using whitespace in options

**Comment by daimonkor** [comment]
ws://192.168.1.33:3300/j5uc9XzVX?colyseusid=xKVTeTs-u&create=true&name=Room 17/02/2019 16:18:49&password=12121213213&requestId=3

**Comment by doorbash** [comment]
Yes I know using whitespace character in `client.options` , `client.id` and `room.options` cause a `java.net.URISyntaxException`

**Comment by daimonkor** [comment]
@doorbash I am trying create like private rooms

**Comment by doorbash** [comment]
@daimonkor Just released v1.2 to resolve this. please check if it is fixed, thanks

**Comment by daimonkor** [comment]
@doorbash I created fork from your repo. I think I will create pull request today.
