### ISSUE TITLE
Bug at Room class

### ISSUE THREAD

**Issue by daimonkor** [doorbash/colyseus-java#5]
@doorbash Hi, please fix small mistake.

```java
 /**
 * Send message to the room handler.
 */
public void send(Object data) {
      if (this.connection != null)
          this.connection.send(Protocol.ROOM_DATA, this.id, data);
      // room is created but not joined yet
      for (Listener listener : listeners) {
          listener.onError(new Exception("send error: Room is created but not joined yet"));
      }
}
```
Problem is with calling ``onError`` listener`s function. I think missing ``else`` code. Thanks for help.

Unity port http://prntscr.com/mov5zy
Js port http://prntscr.com/mov6c2

**Comment by doorbash** [comment]
Fixed. thanks @daimonkor for reporting.

**Comment by daimonkor** [comment]
@doorbash Thanks for support.

**Comment by daimonkor** [comment]
@doorbash I think you can remove pom.xml file from repository, current file auto generate by gradle publish script, for example my pom file was auto generated http://prntscr.com/movtzu

**Comment by doorbash** [comment]
I just realized `pom.xml` file is outdated, just added a missing dependency to it. thanks for mentioning it.
I know but i wanted it to support both `gradle` and `maven`. @daimonkor Thanks for taking your time to dig into the sources I really appreciate it 🙏

**Comment by daimonkor** [comment]
@doorbash Thanks for client and very fast support.
