### ISSUE TITLE
Refactor Client class

### ISSUE THREAD

**Issue by daimonkor** [doorbash/colyseus-java#6]
Please implement current code
http://prntscr.com/mrl49g

I got current error on Android API 18
https://stackoverflow.com/questions/8151766/how-to-catch-java-lang-noclassdeffounderror

Thanks for your support.

**Comment by doorbash** [comment]
Hi @daimonkor ok I will thanks for spotting it.

https://stackoverflow.com/questions/38183027/java-lang-noclassdeffounderror-java-nio-charset-standardcharsets

**Comment by daimonkor** [comment]
@doorbash Thanks for your support.
